Table changes
JackStorror/makersbnb-Code_Breakers pull request #17
Opened 2021-11-09 16:10 UTC by JRMBowers

Implementation of table changes, user story 6 and rename/deletion of database.rb/space.rb. Changes to database table column names.

2021-11-09 16:32 UTC, jjegarcia requested changes

2021-11-09 16:32 UTC, jjegarcia commented on db/migrations/01_makers_bnb.sql
> -CREATE TABLE spaces(id SERIAL PRIMARY KEY, name VARCHAR(60)) ;
can you do space_id, space_name and space_description?

2021-11-09 16:34 UTC, jjegarcia commented on db/migrations/01_makers_bnb.sql
> -CREATE TABLE spaces(id SERIAL PRIMARY KEY, name VARCHAR(60)) ;
also may need to match names to parameters in the code also

2021-11-09 16:38 UTC, jjegarcia commented on app.rb
> +    Space_handler.add_space(name: params[:name], description: params[:description], price_per_night: params[:price_per_night])
could reane to space_name, space_description

2021-11-09 16:38 UTC, jjegarcia commented on model/space_handler.rb
> +  def initialize(id:, name:, description:, price_per_night:)
please rename to space_xxxxxx

2021-11-09 16:38 UTC, jjegarcia commented on model/space_handler.rb
> +    result.map { |space| Space_handler.new(id: space['spaces_id'], name: space['spaces_name'], description: space['spaces_description'], price_per_night: space['price_per_night']) }
please rename to space_xxxxxxx

2021-11-09 16:38 UTC, jjegarcia commented on spec/feature/add_space_spec.rb
> +    expect(result.first['spaces_name']).to eq 'Bat Cave'
please rename to space_xxxxxxx

2021-11-09 16:38 UTC, jjegarcia commented on views/add_space.erb
> +  <input type='text' name='name'>
please rename to space_xxxxxxx

2021-11-09 17:27 UTC, jjegarcia approved these changes

2021-11-09 18:10 UTC, JackStorror reviewed
Yeah just those column names everything else looks spot on!

2021-11-10 07:33 UTC, MarcBrosch approved these changes

2021-11-10 07:33 UTC, merged